services:
  bora-ora-frontend:
    build:
      context: './docker'
      dockerfile: Dockerfile
    environment:
      TZ: "Asia/Seoul"
    container_name: bora-ora-frontend
    hostname: bora-ora-frontend
    domainname: localdomain
    ports:
      - "3000:3000"
      - "8443:443"
    stdin_open: true
    tty: true
    volumes:
      - .:/Workspaces:rw
      - ./docker/storage:/tmp/storage
#    command:
#      - /usr/local/bin/start.sh
    networks:
      - bora-networks

networks:
  bora-networks:
    driver: bridge
