import tw from 'twin.macro';

export default {
    LoginLayoutStyle: {
        LoginImgSection: tw.div`flex flex-nowrap h-screen w-full`,
        LoginImgWrapper: tw.div`hidden md:block md:w-[460px]`,
        LoginImgContainer: tw.div`w-full h-screen border`,
        LoginMainImg: tw.figure`relative h-screen transition-all duration-300 cursor-pointer filter`,
        LoginImg: tw.img`h-screen w-screen object-cover`,
        LoginFigcaption: tw.figcaption`absolute px-4 text-lg text-white bottom-6 flex flex-col items-center w-full`,
        FigTitle: tw.p`text-xl`,
        FigName: tw.p`text-sm`,
        LoginSection: tw.div`flex flex-col items-center justify-center px-6 py-8 mx-auto h-screen lg:py-0`,
        LoginWrapper: tw.div`w-full bg-white rounded-lg shadow md:mt-0 sm:max-w-md xl:p-0`,
        LoginContainer: tw.div`p-6 space-y-4 md:space-y-6 sm:p-8`,
        LoginText: tw.h1`text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl`,
        LoginSubText: tw.h1`text-xl font-bold leading-tight tracking-tight text-blue-700 md:text-2xl`,
        LoginInputSection: tw.div`space-y-4 md:space-y-6`,
        LoginInput: tw.input`bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-pink-600 focus:border-pink-600 block w-full p-2.5`,
        LoginCheckSection: tw.div`flex items-center justify-between`,
        LoginCheckWrapper: tw.div`flex items-start`,
        LoginCheckContainer: tw.div`flex items-center h-5`,
        IdCheckBox: tw.input`w-4 h-4 border border-gray-300 rounded bg-gray-50 focus:ring-2 focus:ring-pink-300`,
        IdCheckSection: tw.div`ml-3 text-sm`,
        IdLabel: tw.label`text-gray-500`,
        SubmitBlueButton: tw.button`w-full text-white bg-blue-600 hover:bg-blue-700 focus:ring-4 focus:outline-none focus:ring-pink-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center`,
        FindSection: tw.div`flex flex-nowrap w-full gap-3 items-center justify-center`,
        FindText: tw.p`cursor-pointer text-sm`,
        KaKaoLoginSection: tw.div`w-full sm:max-w-md pt-1 md:pt-40`,
        KaKaoLoginButton: tw.button`w-full text-white bg-amber-300 hover:bg-amber-400 focus:ring-4 focus:outline-none focus:ring-pink-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center justify-center gap-2`,
        KaKaoIcon: tw.svg`w-5 h-5 fill-black`,
        KaKaoJoinButton: tw.button`w-full text-white bg-amber-300 hover:bg-amber-400 focus:ring-4 focus:outline-none focus:ring-pink-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center justify-center gap-2`,
        EmailJoinButton: tw.button`w-full text-black focus:ring-4 focus:outline-none focus:ring-pink-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center justify-center gap-2`,
        JoinModalSection: tw.div`flex flex-col space-y-4 w-full`,
        JoinText: tw.p`text-xl font-extrabold`,
    },
};
