import tw from 'twin.macro';

export default {
    MatchLayoutStyle: {
        HeaderDivIcon: tw.div`flex cursor-pointer`,
        HeaderDivIcon1: tw.div`flex flex-col items-center py-2`,
        HeaderPIcon: tw.div`text-xs pt-1`,
        DateSectionContainer: tw.section`flex w-full justify-center p-5 bg-white sticky top-0`,
        DateSectionWrapper: tw.div`flex flex-col w-full md:max-w-screen-lg`,
        DateSectionDiv: tw.div`flex w-full`,
        DateSliderSection: tw.div`flex w-full pl-1 items-center justify-center`,
        DateSliderDiv: tw.div`flex flex-col w-full justify-center items-center`,
        DateIndexZeroDiv: tw.div`flex flex-col-reverse w-full items-center justify-center rounded-full bg-blue-400 py-2`,
        DateWeekZeroDiv: tw.div`flex flex-col-reverse w-full items-center justify-center rounded-full py-2`,
        FilteringContainer: tw.div`flex w-full h-full pt-5`,
        // FilteringWrapper: tw.div`grid grid-row-1 grid-flow-col gap-2`,
        FilteringSelectedButton: tw.button`bg-white text-sm text-blue-700 py-1 p-3 rounded-full border border-blue-700 inline-flex items-center`,
        MatchListContainer: tw.section`flex w-full justify-center overflow-auto`,
        MatchListWrapper: tw.div`flex w-full flex-col divide-y scroll-m-0`,
        MatchInfoContainer: tw.div`flex w-full border-b h-20`,
        MatchInfoTime: tw.div`flex flex-none h-full w-32 pl-5 items-center justify-start`,
        P: tw.p``,
        MatchInfoWrapper: tw.div`flex flex-col grow pl-3 justify-center`,
        MatchTitle: tw.p`text-gray-600 text-base font-semibold`,
        MatchSubInfo: tw.p`flex items-center content-center pl-1 text-gray-400 text-xs`,
        MatchButtonContainer: tw.div`flex flex-none justify-end md:w-28`,
        MatchButtonWrapper: tw.div`flex w-full items-center`,
    },
    DetailLayoutStyle: {
        DetailMainSection: tw.main`flex-1 w-full bg-gray-100`,
        MainImg: tw.img`object-fill h-96 w-full`,
        PageSection: tw.figcaption`flex absolute bottom-8 left-1/2 rounded-full w-24 items-center justify-center backdrop-blur-sm bg-white/30 cursor-pointer`,
        DetailMainContainer: tw.div`flex w-full bg-gray-100 gap-2`,
        DetailMainWrapper: tw.div`flex flex-col w-2/3 overflow-y-scroll gap-2`,
        DetailItemSection: tw.div`flex flex-col w-full p-2 bg-white`,
        DetailItem1: tw.div`flex flex-col w-full p-2 bg-gray-200 rounded-3xl`,
        DetailItemContainer: tw.div`flex flex-col w-full space-y-5 p-2`,
        DetailTitle: tw.span`text-base font-semibold`,
        FirstDetailSection: tw.div`flex w-full items-center justify-center`,
        FirstDetailContainer: tw.div`flex flex-col w-full object-center items-center justify-center`,
        FirstDetailIcon: tw.img`h-8 w-8`,
        FirstItemSection: tw.div`flex w-full items-center justify-around`,
        BlueIcon: tw.div`flex h-12 w-10 bg-cover items-center justify-center bg-[url(https://d31wz4d3hgve8q.cloudfront.net/static/img/bibs_blue_back.svg)]`,
        BlueSmIcon: tw.div`flex h-10 w-8 bg-cover items-center justify-center bg-[url(https://d31wz4d3hgve8q.cloudfront.net/static/img/bibs_blue_back.svg)]`,
        YellowIcon: tw.div`flex h-12 w-10 bg-cover items-center justify-center bg-[url(https://d31wz4d3hgve8q.cloudfront.net/static/img/bibs_yellow_back.svg)]`,
        YelloSmIcon: tw.div`flex h-10 w-8 bg-cover items-center justify-center bg-[url(https://d31wz4d3hgve8q.cloudfront.net/static/img/bibs_red_back.svg)]`,
        RedIcon: tw.div`flex h-12 w-10 bg-cover items-center justify-center bg-[url(https://d31wz4d3hgve8q.cloudfront.net/static/img/bibs_red_back.svg)]`,
        RedSmIcon: tw.div`flex h-10 w-8 bg-cover items-center justify-center bg-[url(https://d31wz4d3hgve8q.cloudfront.net/static/img/bibs_yellow_back.svg)]`,
        WhiteText: tw.span`text-lg font-semibold text-white`,
        WhiteSmText: tw.span`text-xs font-semibold text-white`,
        FirstExplain: tw.div`flex flex-col w-full p-2`,
        SecondItemSection: tw.div`flex items-center object-center gap-8`,
        GrayItemSection: tw.div`flex w-full h-20 bg-gray-200 rounded-lg`,
        GrayItem: tw.div`flex w-full flex-col items-center justify-center`,
        MatchItemSection: tw.div`flex w-full h-20 rounded-lg`,
        MatchItemContainer: tw.div`flex w-full flex-col items-center object-center justify-center gap-2`,
        LevelSection: tw.div`flex items-center object-center`,
        ChartSection: tw.div`flex flex-nowrap w-full h-28 justify-between gap-3`,
        ChartItemSection: tw.div`flex flex-col w-full h-full justify-end items-center`,
        ChartItem: tw.div`flex flex-col w-full border bg-gray-100 h-16 object-bottom justify-end`,
        Chart1: tw.div`w-full bg-orange-500 h-0`,
        Chart2: tw.div`w-full bg-orange-500 h-1/5`,
        Chart3: tw.div`w-full bg-orange-500 h-2/5`,
        Chart4: tw.div`w-full bg-orange-500 h-full`,
        Chart5: tw.div`w-full bg-orange-500 h-1/5`,
        ItemCenterGap: tw.div`flex items-center gap-1`,
        ItemCenterGap2: tw.div`flex items-center gap-2`,
        ChartImg: tw.img`w-2/3`,
        ChartExplainSection: tw.div`flex flex-col items-center justify-center`,
        ChartExplainContainer: tw.div`flex w-full justify-start`,
        ChartExplainContainerPl6: tw.div`flex w-full justify-start pl-6`,
        DetailIcon: tw.img`h-4 w-4`,
        DetailItemWrapper: tw.div`grid grid-cols-2 gap-4`,
        TextGraySm: tw.span`text-sm text-gray-600`,
        BorderBar: tw.div`flex flex-col w-full border`,
        DetailItemExplain: tw.div`flex flex-col w-full p-2 space-y-4`,
        MatchDetailTitle: tw.span`text-sm text-gray-500 font-semibold`,
        MatchDetailTitleGray: tw.span`text-sm text-gray-500`,
        MatchDetailTitleGrayUnderline: tw.span`text-sm text-gray-500 underline`,
        SubExplainSection: tw.div`flex pl-8`,
        ExplainSection: tw.div`flex max-w-full`,
        ExplainWrapper: tw.span`w-full text-sm text-gray-500 font-sans text-left whitespace-pre-line`,
        ExplaiContainer: tw.div`flex w-full px-6`,
        ExplainList: tw.ul`list-disc`,
        TableSection: tw.table`w-full border-collapse border border-slate-500`,
        TableTitle: tw.td`text-sm text-gray-500 border border-gray-400 p-1`,
        MatchDetailRightSection: tw.div`flex flex-col h-10 sticky top-0 w-full bg-white`,
        DivideBar: tw.div`border`,
        DetailSubSection: tw.div`flex flex-nowrap w-full items-center justify-between gap-2`,
        BlueTextUnderline: tw.span`text-xs text-blue-500 underline`,
        TextGrayLine: tw.span`text-sm text-gray-300 line-through`,
        EmptySection: tw.section`flex w-full justify-center h-5`,
    },
};
