import tw from 'twin.macro';

export default {
    Bora: {
        ProfileUpdateStyles: {
            Container: tw.section`w-full bg-gray-50 dark:bg-gray-900`,
            Wapper: tw.div`flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0`,
            FormWapper: tw.div`w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700`,
            FormBox: tw.div`p-6 space-y-4 md:space-y-6 sm:p-8`,
            TitleBox: tw.h1`flex justify-center text-xl  font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white`,
            AuthForm: tw.div`space-y-4 md:space-y-6`,
            InputItem: tw.div``,
            InputLabel: tw.label`block mb-2 text-sm font-medium text-gray-900 dark:text-white`,
            Input: tw.input`bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-sky-600 focus:border-sky-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500`,
            Button: tw.button`w-full text-white bg-sky-600 hover:bg-sky-700 focus:ring-4 focus:outline-none focus:ring-sky-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-sky-700 dark:focus:ring-sky-800`,
            ErrorMessage: tw.span`pt-1 font-medium text-xs text-red-500`,
            ProfileImageForm: tw.div`mt-1 flex items-center`,
            ProfileImage: tw.span`inline-block h-12 w-12 rounded-full overflow-hidden bg-gray-100`,
            DefaultProfileImage: tw.img``,
            ProfileInputItem: tw.input`absolute w-0 h-0 mx-0.5`,
            ProfileInputLabel: tw.label`ml-5 bg-gray-50 py-2 px-3 border border-gray-300 rounded-md shadow-sm text-sm leading-4 font-medium text-gray-700 hover:bg-white focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500`,
        },
        ProfileStyles: {
            Container: tw.section`w-full bg-gray-50 dark:bg-gray-900`,
            Wapper: tw.div`flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0`,
            FormWapper: tw.div`w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700`,
            FormBox: tw.div`p-6 space-y-4 md:space-y-6 sm:p-8`,
            TitleBox: tw.h1`flex justify-center text-xl  font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white`,
            AuthForm: tw.div`space-y-4 md:space-y-6`,
            InputItem: tw.div``,
            InputLabel: tw.label`w-48 mb-2 text-sm font-medium text-gray-900 dark:text-white`,
            Input: tw.input`p-6 sm:text-lg p-2.5 focus:outline-none text-gray-500`,
            Button: tw.button`w-full text-white bg-sky-600 hover:bg-sky-700 focus:ring-4 focus:outline-none focus:ring-sky-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-sky-700 dark:focus:ring-sky-800`,
            ErrorMessage: tw.span`pt-1 font-medium text-xs text-red-500`,
            ProfileImageForm: tw.div`mt-1 flex items-center`,
            ProfileImage: tw.span`inline-block h-16 w-16 rounded-full overflow-hidden bg-gray-100`,
            DefaultProfileImage: tw.img``,
            ProfileInputItem: tw.input`absolute w-0 h-0 mx-0.5`,
            ProfileInputLabel: tw.label`ml-5 bg-gray-50 py-2 px-3 border border-gray-300 rounded-md shadow-sm text-sm leading-4 font-medium text-gray-700 hover:bg-white focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500`,
        },
    },
    Auth: {
        AuthStyles: {
            Container: tw.section`w-full bg-gray-50 dark:bg-gray-900`,
            Wapper: tw.div`flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0`,
            FormWapper: tw.div`w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700`,
            FormBox: tw.div`p-6 space-y-4 md:space-y-6 sm:p-8`,
            TitleBox: tw.h1`flex justify-center text-xl  font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white`,
            AuthForm: tw.form`space-y-4 md:space-y-6`,
            InputItem: tw.div``,
            InputLabel: tw.label`block mb-2 text-sm font-medium text-gray-900 dark:text-white`,
            Input: tw.input`bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-sky-600 focus:border-sky-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500`,
            Button: tw.button`w-full text-white bg-sky-600 hover:bg-sky-700 focus:ring-4 focus:outline-none focus:ring-sky-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-sky-700 dark:focus:ring-sky-800`,
            AuthButton: tw.span`flex text-sm font-light text-gray-500 dark:text-gray-400`,
            AuthText: tw.div`ml-2 font-medium text-sky-600 dark:text-blue-500 cursor-pointer`,
            ErrorMessage: tw.span`pt-1 font-medium text-xs text-red-500`,
            ManagerWapper: tw.div`flex items-center justify-between`,
            RememberId: tw.div`flex items-start`,
            CheckBoxWapper: tw.div`flex items-center h-5`,
            RememberTextWapper: tw.div`ml-3 text-sm`,
            RememberTextLabel: tw.label`text-gray-500 dark:text-gray-300`,
            RememberCheckBox: tw.input`w-4 h-4 border border-gray-300 rounded bg-gray-50 focus:ring-4 focus:ring-sky-300 dark:bg-gray-700 dark:border-gray-600 dark:focus:ring-sky-600 dark:ring-offset-gray-800`,
        },
    },
};
